# Generates the per VM secrets and rebuilds the install image with them baked in.

function ConvertTo-WslPath {
    param([string]$WindowsPath)
    $full = [System.IO.Path]::GetFullPath($WindowsPath)
    $drive = $full.Substring(0, 1).ToLower()
    $rest  = $full.Substring(2) -replace '\\', '/'
    return "/mnt/$drive$rest"
}

function New-RandomPassword {
    param([int]$Length = 24)
    # Alphanumeric only, so the value is safe inside YAML, shell and the unlock
    # tooling without any quoting surprises.
    $chars = 'ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnpqrstuvwxyz23456789'
    $bytes = New-Object 'System.Byte[]' $Length
    [System.Security.Cryptography.RandomNumberGenerator]::Create().GetBytes($bytes)
    -join ($bytes | ForEach-Object { $chars[$_ % $chars.Length] })
}

function New-BuildCredentials {
    param([hashtable]$Config)

    $outDir = Join-Path $Config.OutputDir $Config.VmName
    if (-not (Test-Path $outDir)) { New-Item -ItemType Directory -Path $outDir -Force | Out-Null }

    $userPassword  = New-RandomPassword
    $luksPassphrase = New-RandomPassword
    $keyPath = Join-Path $outDir 'id_ed25519'

    if (Test-Path $keyPath) { Remove-Item $keyPath, "$keyPath.pub" -Force -ErrorAction SilentlyContinue }
    # Native Windows OpenSSH key, used to log in and check the finished VM.
    # This runs through cmd.exe so the empty quotes after -N are read as an empty
    # passphrase. PowerShell on its own either drops an empty argument or passes
    # the two quote characters as a real passphrase, so neither form is reliable.
    $keyComment = "build-$($Config.VmName)"
    $kgLine = 'ssh-keygen -q -t ed25519 -N "" -C ' + $keyComment + ' -f "' + $keyPath + '"'
    cmd.exe /c $kgLine | Out-Null
    if (-not (Test-Path "$keyPath.pub")) { throw 'ssh-keygen did not create a key. Check the OpenSSH client install.' }
    $pubKey = (Get-Content "$keyPath.pub" -Raw).Trim()

    $envPath = Join-Path $outDir '.env'
    @"
# Credentials for $($Config.VmName). Generated by the build. Keep this private.
VM_NAME=$($Config.VmName)
HOSTNAME=$($Config.Hostname)
USERNAME=$($Config.Username)
PASSWORD=$userPassword

# Recovery passphrase for the encrypted disk. Normal boots unlock from the TPM
# with no prompt. This is the way in if the TPM binding is ever lost.
LUKS_PASSPHRASE=$luksPassphrase

IP_ADDRESS=$(($Config.IpCidr -split '/')[0])
SSH_KEY=$keyPath
# Log in with:  ssh -i "$keyPath" $($Config.Username)@$(($Config.IpCidr -split '/')[0])
"@ | Set-Content -Path $envPath -Encoding ascii

    Write-Host "   Credentials written to $envPath"

    return @{
        UserPassword   = $userPassword
        LuksPassphrase = $luksPassphrase
        SshPubKey      = $pubKey
        SshKeyPath     = $keyPath
        OutDir         = $outDir
    }
}

function New-AutoinstallImage {
    param(
        [hashtable]$Config,
        [hashtable]$Creds,
        [string]$RepoRoot
    )

    Write-Host '== Building install image =='

    $stage = Join-Path (Join-Path $RepoRoot 'build') $Config.VmName
    $aiDir = Join-Path $stage 'autoinstall'
    New-Item -ItemType Directory -Path $aiDir -Force | Out-Null

    $tpl = Join-Path $RepoRoot 'templates'
    $userData = (Get-Content (Join-Path $tpl 'user-data.tt') -Raw)
    $metaData = (Get-Content (Join-Path $tpl 'meta-data') -Raw)

    $ipOnly = ($Config.IpCidr -split '/')[0]
    $subs = @{
        '__HOSTNAME__'       = $Config.Hostname
        '__USERNAME__'       = $Config.Username
        '__IP_CIDR__'        = $Config.IpCidr
        '__GATEWAY__'        = $Config.Gateway
        '__DNS_LIST__'       = $Config.Dns
        '__SSH_PUBKEY__'     = $Creds.SshPubKey
        '__USER_PASSWORD__'  = $Creds.UserPassword
        '__LUKS_PASSPHRASE__'= $Creds.LuksPassphrase
    }
    foreach ($k in $subs.Keys) {
        $userData = $userData.Replace($k, $subs[$k])
        $metaData = $metaData.Replace($k, $subs[$k])
    }

    # Write with Unix line endings and no trailing BOM. cloud-init is strict.
    $utf8 = New-Object System.Text.UTF8Encoding($false)
    [System.IO.File]::WriteAllText((Join-Path $aiDir 'user-data'), ($userData -replace "`r`n", "`n"), $utf8)
    [System.IO.File]::WriteAllText((Join-Path $aiDir 'meta-data'), ($metaData -replace "`r`n", "`n"), $utf8)
    Copy-Item (Join-Path $tpl 'grub.cfg') (Join-Path $stage 'grub.cfg')
    # Normalise the menu config line endings too.
    $grub = (Get-Content (Join-Path $stage 'grub.cfg') -Raw) -replace "`r`n", "`n"
    [System.IO.File]::WriteAllText((Join-Path $stage 'grub.cfg'), $grub, $utf8)

    $outIso = Join-Path $Config.VmDir ("{0}-autoinstall.iso" -f $Config.VmName)
    if (-not (Test-Path $Config.VmDir)) { New-Item -ItemType Directory -Path $Config.VmDir -Force | Out-Null }

    $srcWsl   = ConvertTo-WslPath $Config.SourceIso
    $outWsl   = ConvertTo-WslPath $outIso
    $stageWsl = ConvertTo-WslPath $stage
    $scriptWsl= ConvertTo-WslPath (Join-Path $RepoRoot 'lib\build-iso.sh')

    Write-Host '   Rebuilding the image with xorriso (this is the only step that uses WSL).'
    $cmd = "sed 's/\r`$//' '$scriptWsl' | bash -s -- '$srcWsl' '$outWsl' '$stageWsl'"
    $logFile = Join-Path $stage 'iso-build.log'

    # xorriso writes its banner and progress to stderr even on success. Send that
    # to a log file so it does not get treated as a failure, and read stdout for
    # the success marker the helper prints when it finishes.
    $prevEap = $ErrorActionPreference
    $ErrorActionPreference = 'Continue'
    $stdout = & wsl.exe -u root -e bash -lc $cmd 2>$logFile
    $ErrorActionPreference = $prevEap

    if (($stdout -join "`n") -notmatch 'ISO_BUILD_OK') {
        if (Test-Path $logFile) { Write-Host (Get-Content $logFile -Raw) }
        throw 'The image rebuild did not finish. See the log above.'
    }
    Write-Host "   Built $outIso"
    return $outIso
}
