# Generates the per VM secrets and rebuilds the install image with them baked in.

function ConvertTo-WslPath {
    param([string]$WindowsPath)
    $full = [System.IO.Path]::GetFullPath($WindowsPath)
    $drive = $full.Substring(0, 1).ToLower()
    $rest = $full.Substring(2) -replace '\\', '/'
    return "/mnt/$drive$rest"
}

function New-RandomPassword {
    param([int]$Length = 24)
    # Alphanumeric only, so the value is safe inside YAML, shell and the unlock
    # tooling without any quoting surprises.
    $chars = 'ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnpqrstuvwxyz23456789'
    $bytes = New-Object 'System.Byte[]' $Length
    [System.Security.Cryptography.RandomNumberGenerator]::Create().GetBytes($bytes)
    -join ($bytes | ForEach-Object { $chars[$_ % $chars.Length] })
}

function Expand-Template {
    # Pure text substitution. Replaces each token with its value and returns the
    # result. Kept separate so it can be unit tested without touching disk.
    param([string]$Content, [hashtable]$Substitutions)
    foreach ($key in $Substitutions.Keys) {
        $Content = $Content.Replace($key, [string]$Substitutions[$key])
    }
    return $Content
}

function Assert-NoUnfilledTokens {
    # Fails if any __PLACEHOLDER__ style token was left behind, which would mean a
    # token name was renamed in the template but not in the substitution table.
    param([string]$Content, [string]$Where)
    if ($Content -match '__[A-Z0-9_]+__') {
        throw "Unfilled placeholder $($matches[0]) left in $Where. Template token and substitution table are out of sync."
    }
}

function New-BuildCredentials {
    param([hashtable]$Config)

    $outDir = Join-Path $Config.OutputDir $Config.VmName
    if (-not (Test-Path $outDir)) { New-Item -ItemType Directory -Path $outDir -Force | Out-Null }

    $userPassword = New-RandomPassword
    $luksPassphrase = New-RandomPassword
    $keyPath = Join-Path $outDir 'id_ed25519'

    if (Test-Path $keyPath) { Remove-Item $keyPath, "$keyPath.pub" -Force -ErrorAction SilentlyContinue }
    # Native Windows OpenSSH key, used to log in and check the finished VM.
    # This runs through cmd.exe so the empty quotes after -N are read as an empty
    # passphrase. PowerShell on its own either drops an empty argument or passes
    # the two quote characters as a real passphrase, so neither form is reliable.
    $keyComment = "build-$($Config.VmName)"
    $kgLine = 'ssh-keygen -q -t ed25519 -N "" -C ' + $keyComment + ' -f "' + $keyPath + '"'
    cmd.exe /c $kgLine | Out-Null
    if (-not (Test-Path "$keyPath.pub")) { throw 'ssh-keygen did not create a key. Check the OpenSSH client install.' }
    $pubKey = (Get-Content "$keyPath.pub" -Raw).Trim()

    $ipOnly = ($Config.IpCidr -split '/')[0]
    $envPath = Join-Path $outDir '.env'
    @"
# Credentials for $($Config.VmName). Generated by the build. Keep this private.
VM_NAME=$($Config.VmName)
HOSTNAME=$($Config.Hostname)
USERNAME=$($Config.Username)
PASSWORD=$userPassword

# Recovery passphrase for the encrypted disk. Normal boots unlock from the TPM
# with no prompt. This is the way in if the TPM binding is ever lost.
LUKS_PASSPHRASE=$luksPassphrase

IP_ADDRESS=$ipOnly
SSH_KEY=$keyPath
# Log in with:  ssh -i "$keyPath" $($Config.Username)@$ipOnly
"@ | Set-Content -Path $envPath -Encoding ascii

    Write-BuildLog "Credentials written to $envPath" INFO

    return @{
        UserPassword   = $userPassword
        LuksPassphrase = $luksPassphrase
        SshPubKey      = $pubKey
        SshKeyPath     = $keyPath
        OutDir         = $outDir
    }
}

function New-AutoinstallImage {
    param(
        [hashtable]$Config,
        [hashtable]$Creds,
        [string]$RepoRoot
    )

    Write-BuildLog "Building the install image" STEP

    $stage = Join-Path (Join-Path $RepoRoot 'build') $Config.VmName
    $aiDir = Join-Path $stage 'autoinstall'
    New-Item -ItemType Directory -Path $aiDir -Force | Out-Null

    $tpl = Join-Path $RepoRoot 'templates'
    $subs = @{
        '__HOSTNAME__'        = $Config.Hostname
        '__USERNAME__'        = $Config.Username
        '__IP_CIDR__'         = $Config.IpCidr
        '__GATEWAY__'         = $Config.Gateway
        '__DNS_LIST__'        = $Config.Dns
        '__SSH_PUBKEY__'      = $Creds.SshPubKey
        '__USER_PASSWORD__'   = $Creds.UserPassword
        '__LUKS_PASSPHRASE__' = $Creds.LuksPassphrase
    }

    $userData = Expand-Template -Content (Get-Content (Join-Path $tpl 'user-data.tt') -Raw) -Substitutions $subs
    $metaData = Expand-Template -Content (Get-Content (Join-Path $tpl 'meta-data') -Raw) -Substitutions $subs
    Assert-NoUnfilledTokens -Content $userData -Where 'user-data'
    Assert-NoUnfilledTokens -Content $metaData -Where 'meta-data'

    # Write with Unix line endings and no BOM. cloud-init is strict about both.
    $utf8 = New-Object System.Text.UTF8Encoding($false)
    [System.IO.File]::WriteAllText((Join-Path $aiDir 'user-data'), ($userData -replace "`r`n", "`n"), $utf8)
    [System.IO.File]::WriteAllText((Join-Path $aiDir 'meta-data'), ($metaData -replace "`r`n", "`n"), $utf8)
    $grub = (Get-Content (Join-Path $tpl 'grub.cfg') -Raw) -replace "`r`n", "`n"
    [System.IO.File]::WriteAllText((Join-Path $stage 'grub.cfg'), $grub, $utf8)

    $outIso = Join-Path $Config.VmDir ("{0}-autoinstall.iso" -f $Config.VmName)
    if (-not (Test-Path $Config.VmDir)) { New-Item -ItemType Directory -Path $Config.VmDir -Force | Out-Null }

    $srcWsl = ConvertTo-WslPath $Config.SourceIso
    $outWsl = ConvertTo-WslPath $outIso
    $stageWsl = ConvertTo-WslPath $stage
    $scriptWsl = ConvertTo-WslPath (Join-Path $RepoRoot 'lib\build-iso.sh')
    $distroArg = if ($Config.ContainsKey('WslDistro') -and $Config.WslDistro) { @('-d', $Config.WslDistro) } else { @() }

    Write-BuildLog "Rebuilding the image with xorriso (the only step that uses WSL)." INFO
    $cmd = "sed 's/\r`$//' '$scriptWsl' | bash -s -- '$srcWsl' '$outWsl' '$stageWsl'"

    # xorriso writes its banner and progress to stderr even on success. Keep that
    # off the error path so it does not abort the build, capture it to the log, and
    # decide success from the marker the helper prints on stdout.
    $prevEap = $ErrorActionPreference
    $ErrorActionPreference = 'Continue'
    $output = & wsl.exe @distroArg -u root -e bash -lc $cmd 2>&1
    $ErrorActionPreference = $prevEap
    $output | Write-NativeOutputToLog

    if (($output -join "`n") -notmatch 'ISO_BUILD_OK') {
        throw 'The image rebuild did not finish. See the build log for the xorriso output.'
    }
    Write-BuildLog "Built $outIso" INFO
    return $outIso
}
